// require('dotenv').config()
const express = require('express')
const passport = require('passport')
const session = require('express-session')
const bodyParser = require('body-parser')
const env = require('dotenv')
const exphbs = require('express-handlebars')
const path = require("path")

var app = express()